apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-kubectl-role-binding
subjects:
  - kind: ServiceAccount
    name: exec-kubectl
roleRef:
  kind: Role
  name: exec-kubectl-role
  apiGroup: rbac.authorization.k8s.io
